-- 접속자 확인
SELECT USER FROM DUAL;

SELECT * FROM MEMBER;

CREATE TABLE MEMBER(
	ID NUMBER PRIMARY KEY,
	EMAIL varchar2(255),
	PASSWORD varchar2(100),
	NAME varchar2(100),
	REGDATE DATE
);
--------- product(no) 시퀀스 생성 ---------
CREATE SEQUENCE MEMBER_ID_SEQ
   START WITH 1
   INCREMENT BY 1;

-- 트리거를 이용하여 자동으로 번호 입력되도록 --
CREATE OR REPLACE TRIGGER TRI_MEMBER_ID_SEQ
BEFORE INSERT ON MEMBER
FOR EACH ROW 
BEGIN 
   IF INSERTING AND:NEW.ID IS NULL THEN
      SELECT MEMBER_ID_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
   END IF;
END;

DROP TRIGGER TRI_PRODUCT_NO_SEQ;


