iNSERT INTO MEMBER(EMAIL, PASSWORD, NAME, REGDATE) VALUES('test@test.co.kr', '1111', 'test', '2020-09-28');
iNSERT INTO MEMBER(EMAIL, PASSWORD, NAME, REGDATE) VALUES('test2@test.co.kr', '2222', 'test2', '2020-09-28');

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE FROM MEMBER WHERE email = 'test@test.co.kr';

UPDATE MEMBER
   SET EMAIL
 WHERE ID = ?;

DELETE FROM MEMBER WHERE ID = ?;
